### ISSUE TITLE
fix sidebar responsivenesss

### ISSUE THREAD

**Issue by noworneverev** [charludo/ycms#134]
### Motivation

After adding the document to the sidebar #133 , it's a little bit crowded for sidebar in small screens, because of the bottom fixed elements. It become even worse when minimize the window.

### Screenshots

![image](https://github.com/charludo/ycms/assets/18380064/ff85bb56-9f56-4d6a-9c1e-bad8f2777501)
![image](https://github.com/charludo/ycms/assets/18380064/0f11535f-3170-4604-9274-dae77683cb64)

**Comment by charludo** [comment]
@noworneverev Could you check if this also happens on your physical phone? Because I can't reproduce it except by making the browser mobile view super short.

TBH I like how the accessibility options/the timetravel/the copyright/... currently stick to the bottom, and the changes in the PR undo that

**Comment by noworneverev** [comment]
![Screenshot_20240116-194454](https://github.com/charludo/ycms/assets/18380064/cbe695c6-1230-4701-8a00-892756fbdc34)
Simply turn your phone to horizontal view can reproduce the issue.

**Comment by charludo** [comment]
> ![Screenshot_20240116-194454](https://private-user-images.githubusercontent.com/18380064/297158094-cbe695c6-1230-4701-8a00-892756fbdc34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzE3NDMsIm5iZiI6MTcwNTQzMTQ0MywicGF0aCI6Ii8xODM4MDA2NC8yOTcxNTgwOTQtY2JlNjk1YzYtMTIzMC00NzAxLThhMDAtODkyNzU2ZmJkYzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE4NTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYTBjMDk1YjlkYWI4ODU4Mzc2ZTdkODVkNTY4NzY4YTI3ZmFjNDI0MmI0N2NmM2Y3NWQyMzM0YzJiYjBjMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xDo33VZJLMRF3wv6lkIRSQ8805TtgRYw9c05N58OAEA) Simply turn your phone to horizontal view can reproduce the issue.

OK, fair 😄 
I have an idea, I'll comment on the PR.
