### ISSUE TITLE
Patient assignment flow/view

### ISSUE THREAD

**Issue by charludo** [charludo/ycms#44]
### Motivation

In the WardView, a list of unassigned patients should be given and options for assigning them need to exist.

### Proposed Solution

- "Unassigned patients" box in the top row, showing number of unassigned and buttons for "manually assign" and "suggest assignment"
- "suggest assignment" should do nothing for now
- "manually assign" opens a sidepanel with unassigned users, with button "Assign" 
- clicking "Assign" closes the sidebar, colors room cards based on if the room is a good fir (age, gender, insurance status)

We probably sould show patient information somewhere while assigning them. It should also be possible to go againsty age and gender recommendations (with a warning)

**Comment by noworneverev** [comment]
I suggest directing to a new page when assigning the patient. The side panel is too small to accommodate that much information and those actions.

**Comment by charludo** [comment]
> I suggest directing to a new page when assigning the patient. The side panel is too small to accommodate that much information and those actions.

True, it's a lot of information... But on the other hand redirecting breaks the work flow quite a bit, I'd say 😅 The idea behind the side panel (not only for assigning, but also already assigned patients) was that the user would not have to leave the page. 

Maybe we could rearrange the side panel somewhat?

There will almost never be more than two patients in a room anyways, so we don't necessarily have to display them as a row in a table. We could also for example do a card/box per patient, so they'd have more vertical space.

**Comment by charludo** [comment]
> > I suggest directing to a new page when assigning the patient. The side panel is too small to accommodate that much information and those actions.
> 
> True, it's a lot of information... But on the other hand redirecting breaks the work flow quite a bit, I'd say 😅 The idea behind the side panel (not only for assigning, but also already assigned patients) was that the user would not have to leave the page).
> 
> Maybe we could rearrange the side panel somewhat?
> 
> There will almost never be more than two patients in a room anyways, so we don't necessarily have two display them as a row in a table. We could also for example do a card/box per patient, so they'd have more vertical space.

Actually, I'm not sure why we need more space, since new patients don't need a discharge button, could we not show the "assign" button where the "discharge" button is for current patients?

**Comment by SnehaR26** [comment]
I can take the "suggest assignment" part. I am working on a pseudo algorithm to assign beds for the standard case of 28 patients to 28 beds.

**Comment by charludo** [comment]
> I can take the "suggest assignment" part. I am working on a pseudo algorithm to assign beds for the standard case of 28 patients to 28 beds.

We don't need to implement that part ourselves, we get a heuristic from Tabea.

If we want to we can do it additionally, later on. But for the MVP I'd say let's focus on the visualization part 😅
