### ISSUE TITLE
Add possibility to manage bed assignment

### ISSUE THREAD

**Issue by noworneverev** [charludo/ycms#49]
### Motivation
There should be possibility to manage the bed assignement

### Proposed Solution
- Add a management page for bed assignment
- Add functionality to create, update and delete bed assignment

**Comment by charludo** [comment]
Isn't this a duplicate of #44?

**Comment by noworneverev** [comment]
> Isn't this a duplicate of #44?

Ah, I didn't notice that. I will close this one.
